enhancements to dgrep to support PDS wildcards enhancements to pcatalog and dlsall to show verbose support mark 'hlq' as requiring 'sh'

diff --git a/utils/dgrep b/utils/dgrep
--- a/utils/dgrep
+++ b/utils/dgrep
@@ -2,18 +2,60 @@
 # Search all datasets matching the pattern for a string, e.g. dgrep IEFPROC sys1.* would search for IEFPROC in all datasets matching SYS1.*
 # Datasets may be sequential datasets or partitioned datasets. If the dataset is partitioned, the search will go across all members of the dataset.
 #
-if [ -z "$2" ]; then
+
+verbose() {
+	if [[ ${verbose} -eq 1 ]]; then
+		echo $*
+	fi
+}
+
+set -o noglob
+#set -x
+ignorecase=0
+debug=0
+verbose=0
+while getopts ":ivd" opt; do
+  case ${opt} in
+    d )
+      debug=1
+      ;;
+    i )
+      ignorecase=1
+      ;;
+    v )
+      verbose=1
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      syntax
+      exit 4
+      ;;
+  esac
+done
+shift $(expr $OPTIND - 1 )
+if [ $# -ne 2 ]; then
 	echo 'dgrep <str> <dataset-pattern>'
         echo '  example: dgrep rexx IBMUSER.MVSCMD.TSO.* (search for rexx (case insensitive) inn all datasets of the pattern IBMUSER.MVSCMD.TSO.*)'
-        exit 16
-else
-	str=$1;
-	datasetpattern=$2;
-	datasetpattern=$(echo ${datasetpattern} | tr '[:lower:]' '[:upper:]')
+	exit 16
 fi
-datasets=`echo " LISTCAT -\n ENTRIES("${datasetpattern}")\n" | mvscmdauth --pgm=idcams --sysprint=* --sysin=stdin | awk '/0NONVSAM/ { print $3 }' `
+
+str=$1;
+datasetpattern=$2;
+datasetpattern=$(echo ${datasetpattern} | tr '[:lower:]' '[:upper:]')
+
+args="SRCHCMP,IDPRFX,NOSUMS,LONGLN,NOPRTCC"
+if [[ ${ignorecase} -eq 1 ]]; then
+	args=${args}",ANYC"
+fi
+datasets=`dlsraw ${datasetpattern} | awk '/NONVSAM/ { print $2 }' `
 for dataset in ${datasets}; do
-	echo "SRCHFOR '"${str}"'\n" | 
-         mvscmd --pgm=isrsupc --args='SRCHCMP,ANYC,IDPRFX,NOSUMS,LONGLN,NOPRTCC' --newdd=${dataset} --outdd=* --sysin=stdin | 
-         awk '!/  ISRSUPC/';
+	verbose "Searching dataset: " ${dataset}
+	echo "SRCHFOR '"${str}"'" | 
+         mvscmd --pgm=isrsupc --args=${args} --newdd=${dataset} --outdd=* --sysin=stdin | 
+         awk '!/  ISRSUPC/' | 
+	 awk '/LINE-#  SOURCE SECTION                    SRCH DSN:/ { dsn=$6; next; } 
+	      / --------- STRING\(S\) FOUND -------------------/ { mem=$1; next; }
+	      // { if ($1 != "") { print dsn"("mem"):"$0; }}'
+	     
+
 done
diff --git a/utils/dls b/utils/dls
--- a/utils/dls
+++ b/utils/dls
@@ -8,24 +8,11 @@
 #set -x
 
 ListBasic() {
-(
- if [ "$2" = "*" ]; then
-   pattern="LEVEL($1) HISTORY"
- else
-   pattern="ALL ENTRIES($1)"
- fi
- echo " LISTCAT ${pattern}" | 
-   mvscmdauth --pgm=idcams --sysprint=* --sysin=stdin | 
-   awk '/0NONVSAM/ { print $3 }'
-)
+	dlsraw $* | awk '/NONVSAM/ { print $2 }'
 }
 
 ListDetails() {
- if [ "$2" = "*" ]; then
-   pattern="('$1') HISTORY LEVEL"
- else
-   pattern="('$1') HISTORY"
- fi
+ pattern="('$1') HISTORY"
  tsocmd "listds ${pattern}" 2>/dev/null |
    awk 'BEGIN { inHeaderA=0; inHeaderB=0; ds=""; vol=""; recfm=""; lrecl=""; blksize=""; created=""; dsorg=""; }
        /--RECFM-LRECL-BLKSIZE-DSORG-CREATED---EXPIRES---SECURITY/ { inHeaderA=1; next; }
@@ -44,33 +31,46 @@ ListDetails() {
       { inHeaderA=0; inHeaderB=0; ds=$1; vol=""; recfm=""; lrecl=""; blksize=""; dsorg=""; created=""; next; }
      '
 }
+verbose() {
+	if [[ ${verbose} -eq 1 ]]; then
+		echo $*
+	fi
+}
 
-
-if [ -z "$1" ]; then
+set -o noglob
+details=0
+debug=0
+verbose=0
+while getopts ":lvd" opt; do
+  case ${opt} in
+    d )
+      debug=1
+      ;;
+    l )
+      details=1
+      ;;
+    v )
+      verbose=1
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      syntax
+      exit 4
+      ;;
+  esac
+done
+shift $(expr $OPTIND - 1 )
+if [ $# -ne 1 ]; then
 	echo 'Syntax: dls [-l] <dataset-prefix>'
 	echo 'Example 1: dls IBMUSER.MVSCMD.* : list all datasets that start with IBMUSER.MVSCMD'
-	echo 'Example 2: dls -l IBMUSER.MVSCMD.C : list the details of the dataset IBMUSER.MVSCMD.C'
 	exit 16
 fi
-if [ "$1" = "-l" ]; then 
-	details=1
-	datasetpattern=$2;
-else
-	details=0
-	datasetpattern=$1;
-fi
-datasetpattern=$(echo ${datasetpattern} | tr '[:lower:]' '[:upper:]');
-filename=$(basename -- "$datasetpattern"); extension="${filename##*.}"; file="${filename%.*}"; 
 
-if [[ "${extension}" = "*" || "${extension}" = "**" ]]; then 
-	option="*"
-	pattern=${file}
+if [ "${details}" == 1 ]; then 
+	files=`ListBasic "$*"`
+	for f in $files; do
+		ListDetails "$f"
+	done
 else
-	option=""
-	pattern="${file}.${extension}"
-fi
-if [ ${details} -gt 0 ]; then
-	ListDetails "${pattern}" "${option}";
-else
-	ListBasic "${pattern}" "${option}";
+	ListBasic "$*"
 fi
