enhanced some of the tools (still much more to be done)

diff --git a/utils/drm b/utils/drm
--- a/utils/drm
+++ b/utils/drm
@@ -1,11 +1,53 @@
+#!/bin/sh
 #
 # remove a dataset
 #
+function syntax {
+	echo "Syntax: drm [-f] <fully-qualified dataset>"
+	echo " -f : if the dataset does not exist, do not issue a message"   
+}
+#set -x
+force=0
+while getopts ":f" opt; do
+  case ${opt} in
+    f )
+      force=1
+      shift $(expr $OPTIND - 1 )
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      syntax
+      exit 4
+      ;;
+  esac
+done
+
 if [[ $# -ne 1 ]]; then
-	echo "Syntax: drm <fully-qualified dataset>"
-	exit 16
+	syntax
+	exit 4
 fi
 ds=$1
 ds=$(echo ${ds} | tr '[:lower:]' '[:upper:]')
-tsocmd "DELETE '${ds}'"
-exit $?
+name="del$$"
+err=/tmp/${name}.err
+out=/tmp/${name}.out
+tsocmd "DELETE '${ds}'" >$out 2>$err
+rc=$?
+if [[ ${rc} -gt 0 ]]; then
+  if [[ ${force} -gt 0 ]]; then
+    grep -q "IDC3012I" <$out # look for 'dataset not found' message
+    if [[ $? -eq 1 ]]; then
+      cat $err
+      cat $out
+    else
+      rc=0
+    fi
+  else 
+    cat $err
+    cat $out
+  fi
+else
+  rm -f $out
+  rm -f $err
+fi
+exit ${rc}
diff --git a/utils/dtouch b/utils/dtouch
--- a/utils/dtouch
+++ b/utils/dtouch
@@ -5,13 +5,14 @@
 #set -x
 export ME=$0
 function syntax {
-  echo "${ME} [<options>]"
+  echo "${ME} [<options>] [<dataset name>]"
   echo " where <options> can be one or more of:"
+  echo " -a [verbose allocation output]"
+  echo " -v [verbose name output]"
   echo " -t<dataset type>"
   echo " -s<dataset primary size> (in bytes)"
   echo " -r<record format>"
   echo " -l<logical record length>"
-  echo " -n<dataset name>"
   echo " -d<data class name> [required for SMS-managed datasets. All VSAM datasets are SMS-managed]"
   echo " -k<key offset>:<key length> [required for Keyed Sequential Datasets (KSDS)]"
   echo " <dataset type> may be one of: KSDS, ESDS, RRDS, SEQ, PDS, PDSE. Default is a PDSE"
@@ -19,7 +20,7 @@ function syntax {
   echo "   Size may include a suffix of K (kilobytes), M (megabytes), G (gigabytes)"
   echo " <record format> is one of FB, VB, U. Default is FB"
   echo " <logical record length> is expressed in bytes (for VB, this includes the prefix area). Default is 80 for FB, 137 for FB, 0 for U"
-  echo " <dataset name> is the name of the dataset to allocate. Default is a temporary, generated name." 
+  echo " <dataset name> is the name of the dataset to allocate. If no dataset name is specified, a generated dataset name will be created." 
 } 
   
 function clean {
@@ -27,6 +28,7 @@ function clean {
   str=`print ${str} | tr [:lower:] [:upper:]`
   print "${str##[=]}"
 }
+
 function tempname {
   count=$1
   hlq=`hlq`
@@ -35,6 +37,7 @@ function tempname {
   process=`printf "P%7.7X" $$`
   echo "${hlq}.${time}.${counter}.${process}"
 }
+
 export INVALID=-1
 function getNumber {
   str=$1
@@ -42,7 +45,7 @@ function getNumber {
     (*[!0-9]*|'') value=${INVALID};;
     (*)           value=${str};;
   esac
-  echo ${value}
+  echo "${value}"
 }
 
 function normalizeSize {
@@ -63,7 +66,7 @@ function normalizeSize {
   if [ ${value} -eq ${INVALID} ]; then
     echo ${INVALID};
   else
-    if [[ ${smsinfo} == "" ]]; then
+    if [[ "${smsinfo}" == "" ]]; then
       if [ ${multiplier} -gt 1000 ]; then
         tracks=`echo $((${value} * (${multiplier} / ${BYTES_PER_TRACK}) + 1 ))`
       else
@@ -85,8 +88,10 @@ key=""
 keyoff=${INVALID}
 keylen=${INVALID}
 dataclass=""
+verboseName=0
+verboseAllocation=0
 
-while getopts ":t:s:r:l:n:k:d:" opt; do
+while getopts ":t:s:r:l:k:d:va" opt; do
   case ${opt} in
     t )
       type=`clean ${OPTARG}`
@@ -100,14 +105,17 @@ while getopts ":t:s:r:l:n:k:d:" opt; do
     l )
       lrecl=`clean ${OPTARG}`
       ;;
-    n )
-      name=`clean ${OPTARG}`
-      ;;
     k )
       key=`clean ${OPTARG}`
       ;;
     d )
       dataclass=`clean ${OPTARG}`
+      ;;
+    v )
+      verboseName=1
+      ;;
+    a )
+      verboseAllocation=1
       ;;
     \?)
       echo "Invalid option: -$OPTARG" >&2
@@ -116,6 +124,17 @@ while getopts ":t:s:r:l:n:k:d:" opt; do
       ;;
   esac
 done
+shift $(expr $OPTIND - 1 )
+if test $# -eq 1; then
+  name=`clean "${1}"`
+  shift
+fi 
+
+if test $# -gt 0; then
+  echo "Unexpected parameters specified: $*"
+  syntax
+  exit 16
+fi
 
 if [[ "${recfm}" == "FB" ]]; then
   recfm="RECFM(F,B)"
@@ -124,16 +143,16 @@ if [[ "${recfm}" == "FB" ]]; then
   fi
 elif [[ "${recfm}" == "VB" ]]; then 
   recfm="RECFM(V,B)"
-  if [[ "${lrecl} == "" ]]; then
+  if [[ "${lrecl}" == "" ]]; then
     lrecl="137"
   fi
 elif [[ "${recfm}" == "U" ]]; then
   recfm="RECFM(U)"
-  if [[ "${lrecl} == "" ]]; then
+  if [[ "${lrecl}" == "" ]]; then
     lrecl="0"
   fi
 else
-  echo "Invalid record format specified. Valid options are: FB, VB or U"
+  echo "Invalid record format specified. Valid options are: FB, VB or U" 
   exit 4
 fi
 
@@ -142,15 +161,15 @@ if [[ "${lrecl}" == "80" ]]; then
   blksize="BLKSIZE(3120)"
 elif [[ "${lrecl}" == "137" ]]; then
   lrecl="LRECL(${lrecl})"
-  blksize="1370"
+  blksize="BLKSIZE(1370)"
 elif [[ "${lrecl}" == "0" ]]; then
   lrecl="LRECL(${lrecl})"
-  blksize="32760"
+  blksize="BLKSIZE(32760)"
 else
   lrecl="LRECL(${lrecl})"
-  blksize="32760"
+  blksize="BLKSIZE(32760)"
 fi
-if [[ ${dataclass} == "" ]]; then
+if [[ "${dataclass}" == "" ]]; then
   lrecl="${lrecl} ${blksize}"
 fi
 
@@ -158,18 +177,22 @@ if [[ "${key}" != "" ]]; then
   keyoff=`echo ${key} | cut -d':' -f 1`
   keylen=`echo ${key} | cut -d':' -f 2`
 fi
-keyoff=`getNumber ${keyoff}`
-keylen=`getNumber ${keylen}`
+keyoff=`getNumber "${keyoff}"`
+keylen=`getNumber "${keylen}"`
 
 if [[ "${type}" == "PDSE" ]]; then
   type="DSNTYPE(LIBRARY,2) DSORG(PO)"
 elif [[ "${type}" == "PDS" ]]; then
   type="DSNTYPE(PDS) DSORG(PO)"
 elif [[ "${type}" == "SEQ" ]]; then
-  type="DSNTYPE(LARGE) DSNTYPE(EXTREQ) DSORG(PS)"
+  if [[ "${dataclass}" == "" ]]; then
+    type="DSNTYPE(BASIC) DSORG(PS)"
+  else 
+    type="DSNTYPE(LARGE) DSNTYPE(EXTREQ) DSORG(PS)"
+  fi
 elif [[ "${type}" == "KSDS" ]]; then
-  if [[ "${dataclass}" == "" || "${keyoff}" = "${INVALID}" || "${keylen}" = "${INVALID}" ]]; then
-    echo "You must specify a dataclass, key offset and ken length for a KSDS dataset"
+  if [[ "${dataclass}" == "" || "${keyoff}" == "${INVALID}" || "${keylen}" == "${INVALID}" ]]; then
+    echo "You must specify a dataclass, key offset and ken length for a KSDS dataset" >&2
     syntax
     exit 4
   fi
@@ -177,22 +200,22 @@ elif [[ "${type}" == "KSDS" ]]; then
   recfm=""
 elif [[ "${type}" == "ESDS" ]]; then
   if [[ "${dataclass}" == "" ]]; then
-    echo "You must specify a dataclass for an ESDS dataset"
+    echo "You must specify a dataclass for an ESDS dataset" >&2
     syntax
     exit 4
   fi
-  type="DSNTYPE(EXTREQ) RECORG(ES))"
+  type="DSNTYPE(EXTREQ) RECORG(ES)"
   recfm=""
 elif [[ "${type}" == "RRDS" ]]; then
   if [[ "${dataclass}" == "" ]]; then
-    echo "You must specify a dataclass for an RRDS dataset"
+    echo "You must specify a dataclass for an RRDS dataset" >&2
     syntax
     exit 4
   fi
   type="DSNTYPE(EXTREC) RECORG(RR)"
   recfm=""
 else
-  echo "Invalid dataset type specified. Valid options are: PDS,PDSE,SEQ,KSDS,ESDS,RRDS"
+  echo "Invalid dataset type specified. Valid options are: PDS,PDSE,SEQ,KSDS,ESDS,RRDS" >&2
   exit 4
 fi
 if [[ "${dataclass}" != "" ]]; then
@@ -201,11 +224,28 @@ fi
 if [[ "${name}" == "" ]]; then
   name=`tempname 000`   
 fi
-if [[ "${#name}" -gt 44 ]]; then
-  echo "Invalid name. Name must be less than 44 characters."
+if [[ ${#name} -gt 44 ]]; then
+  echo "Invalid name. Name must be less than 44 characters." >&2
   exit 4
 fi
-name="DATASET('${name}')"
+dsname="DATASET('${name}')"
 
 size=`normalizeSize ${size} ${dataclass}`
-echo "alloc ${name} ${type} ${recfm} ${lrecl} ${size} NEW CATALOG"
+err=/tmp/${name}.$$.err
+out=/tmp/${name}.$$.out
+cmd="alloc ${dsname} ${type} ${recfm} ${lrecl} ${size} NEW CATALOG"
+if [[ ${verboseAllocation} -gt 0 ]]; then
+  echo "${cmd}"
+fi
+tsocmd "${cmd}" >${out} 2>${err}
+rc=$?
+if [[ ${rc} -gt 0 ]]; then
+  cat ${err} >&2
+  cat ${out} 
+else 
+  if [[ ${verboseName} -gt 0 ]]; then
+    echo "${name}"
+  fi
+  rm -f ${out} ${err}
+fi
+exit ${rc}
diff --git a/utils/vtocls b/utils/vtocls
--- a/utils/vtocls
+++ b/utils/vtocls
@@ -1,18 +1,130 @@
 #
 # list datasets in a volume
+# IEHLIST format: https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.idau100/u1262.htm
+# Explanation of extents: http://publibfp.boulder.ibm.com/cgi-bin/bookmgr/BOOKS/dgt2d450/1.3.4?ACTION=MATCHES&REQUEST=extent&TYPE=FUZZY&SHELF=&DT=20060524093000&CASE=&searchTopic=TOPIC&searchText=TEXT&searchIndex=INDEX&rank=RANK&ScrollTOP=FIRSTHIT#FIRSTHIT
 #
+# Example output for a PO and PS datasets from IEHLIST
+# 0---------------DATA SET NAME----------------  SER NO  SEQNO  DATE.CRE  DATE.EXP  DATE.REF  EXT DSORG RECFM OPTCD BLKSIZE
+#  TSTRADM.TEST.DTOUCH.BASIC                     USER20      1  2018.161    00.000  2018.161    1  PO   FB     00    32720 
+# 0SMS.IND   LRECL  KEYLEN  INITIAL ALLOC  2ND ALLOC    EXTEND       LAST BLK(T-R-L)  DIR.REM  F2 OR F3(C-H-R)  DSCB(C-H-R)
+#  S  BI        80            TRKS             107            5MB                                                 0   1   6
+#  EATTR                                                                                                                   
+#  NS                                                                                                                      
+# 0            EXTENTS  NO  LOW(C-H)   HIGH(C-H)                                                                           
+#                         0 25604  0    25611  2                                                                           
+#                                  ----UNABLE TO CALCULATE EMPTY SPACE.                                                    
+# 0                                                                                                                        
+# 1                              SYSTEMS SUPPORT UTILITIES---IEHLIST                               PAGE    2               
+# -                                                                                                                        
+# 0---------------DATA SET NAME----------------  SER NO  SEQNO  DATE.CRE  DATE.EXP  DATE.REF  EXT DSORG RECFM OPTCD BLKSIZE
+#  TSTRADM.TEST.PS                               USER20      1  2018.161    00.000  2018.161    1  PS   FB     00    27920 
+# 0SMS.IND   LRECL  KEYLEN  INITIAL ALLOC  2ND ALLOC    EXTEND       LAST BLK(TTTT-R) DIR.REM  F2 OR F3(C-H-R)  DSCB(C-H-R)
+#  S R E        80            TRKS              94            5MB            0    1                               0   1   7
+#  EATTR                                                                                                                   
+#  NS                                                                                                                      
+# 0            EXTENTS  NO  LOW(C-H)   HIGH(C-H)                                                                           
+#                         0 25611  3    25617  6                                                                           
+#                                  ----ON THE ABOVE DATA SET,THERE ARE         93 EMPTY TRACK(S).                          
+# 0 
+#
+# Example output from vtocls:
+#0---------------DATA SET NAME----------------  SER NO   SEQNO  DATE.CRE  DATE.EXP  DATE.REF  EXT DSORG RECFM OPTCD BLKSIZE SMS.IND   LRECL  KEYLEN  INITIAL ALLOC  2ND ALLOC EXTEND LAST BLK(T-R-L) DIR.REM F2 OR F3(C-H-R) DSCB(C-H-R) EATTR EXTENTS NO LOW(C-H)   HIGH(C-H)
+# TSTRADM.TEST.PS                               USER20	     1  2018.161    00.000  2018.161    1  PS   FB     00    27920  S  B      80	            TRKS             107      5MB                                           0   1   6   NS           0   25604 0    25611 2
+#
+
 if [[ $# -ne 1 ]]; then
 	echo "Syntax: vtocls <vol>"
 	exit 16
 fi
 vol=$1
 vol=$(echo ${vol} | tr '[:lower:]' '[:upper:]')
-vtoc=`echo "  LISTVTOC FORMAT,VOL=3390=${vol}\n" | mvscmd --pgm=iehlist --args='' --dd2=${vol},vol  --sysin=stdin --sysprint=*` 
+ds="SYS1.VVDS.V"${vol}
+vtoc=`mvscmd --pgm=iehlist --sysprint=* --dd=${ds} --sysin=stdin <<zzz
+ LISTVTOC FORMAT,VOL=3390=${vol}
+zzz`
 rc=$?
 if [[ ${rc} -gt 0 ]] ; then
-	echo "Volume ${vol} not found"
-	exit 16
+  echo "Volume ${vol} not found"
+  exit 16
 else 
-	echo "$vtoc" | awk '/0---------------DATA SET NAME----------------/ { processedHeader = 1 } !/0---------------DATA SET NAME----------------/ { if (processedHeader) { print; processedHeader=0 } }'
+  echo "$vtoc" | awk '
+	function chunk(str,start,end,lineNum) { return substr(str,(lineNum*121)+start+1,end-start+1); }
+	function ltrim(s) { sub(/^[ \t\r\n]+/, "", s); return s }
+	function rtrim(s) { sub(/[ \t\r\n]+$/, "", s); return s }
+	function trim(s)  { return rtrim(ltrim(s)); }
+	function trspace(s) { gsub(/[ ]/, "-", s); return s }
+	function rmspace(s) { gsub(/[ ]/, "", s); return s }
+	BEGIN {
+	BYTES_PER_TRACK=56664;
+	TRACKS_PER_CYL=15;
+	dsNameS=1; dsNameF=44; serNoS=47; serNoF=52; seqNoS=55; seqNoF=59; crtS=62; crtF=69; expS=72; expF=79; refS=82; refF=89;
+	extS=92; extF=94; dsOrgS=96; dsOrgF=100; recFmS=101; recFmF=108; optCdS=109; optCdF=113; blkSzS=114; blkSzF=120
+
+	smsIndS=1; smsIndF=7; lReclS=11; lReclF=15; keyLenS=18; keyLenF=23; pAllocS=26; pAllocF=38; sAllocS=41; sAllocF=59; 
+	lastTRLS=67; lastTRLF=81; dirRemS=84; dirRemF=90; f2OrF3S=93; f2OrF3F=107; dscbS=110; dscbF=120;
+	}
+	/0---------------DATA SET NAME----------------  SER NO  SEQNO  DATE.CRE  DATE.EXP  DATE.REF  EXT DSORG RECFM OPTCD BLKSIZE/ { 
+		printing=1; line=""; next; 	
+	}
+	/0SMS.IND   LRECL  KEYLEN  INITIAL ALLOC  2ND ALLOC/ { 
+		next; 
+	}
+	/ EATTR/ { 
+		next; 
+	}
+	/0            EXTENTS  NO  LOW(C-H)   HIGH(C-H)/ { 
+		next;
+	}
+	/1                              SYSTEMS SUPPORT UTILITIES/ {
+		next;
+	}
+	/ ----/ { 
+#		print line;
+		dsName=chunk(line,dsNameS,dsNameF,0);
+		serNo=chunk(line,serNoS,serNoF,0);
+		ref=chunk(line,refS,refF,0);
+		dsOrg=trim(chunk(line,dsOrgS,dsOrgF,0));
+		recFm=rmspace(chunk(line,recFmS,recFmF,0));
+		lRecl=trim(chunk(line,lReclS,lReclF,1));
+		blkSz=trim(chunk(line,blkSzS,blkSzF,0));
+		smsInd=trspace(chunk(line,smsIndS,smsIndF,1));
+		ext=chunk(line,extS,extF,0);
+		pAlloc=chunk(line,pAllocS,pAllocF,1);
+		sAlloc=chunk(line,sAllocS,sAllocF,1);
+		lastTRL=trim(chunk(line,lastTRLS,lastTRLF,1));
+		if (trim(pAlloc) == "TRKS" || trim(pAlloc) == "TRKS CONTIG") {
+			bytes=(BYTES_PER_TRACK*(sAlloc+1)*ext);
+		} else if (trim(pAlloc) == "CYLS") {
+			bytes=(BYTES_PER_TRACK*TRACKS_PER_CYL*(sAlloc+1)*ext);
+		} else {
+			bytes="?"
+		}
+		if (trim(smsInd) == "") {
+			smsInd = "      -";
+		}
+		keyLen=chunk(line,keyLenS,keyLenF,1);
+		if (trim(keyLen) == "") {
+			keyLen = "    -";
+		}
+		n=split(lastTRL,size,/[ ]+/);
+		if (n > 1) {
+			bytes = ((size[1]*BYTES_PER_TRACK) + (blkSz*size[2]))
+		} else {
+			bytes = "?"
+		}
+		printf "%44s %3s %3s %5d %15s\n", dsName, dsOrg, recFm, lRecl, bytes
+		printing=0;
+		next;
+	}
+	/-/ {
+		next;
+	}
+	// {
+		if (printing) {
+			line = line $0;
+		}
+		next;
+	}
+  '
 fi
 exit 0
